error_reporting = E_ALL
display_errors = On
display_startup_errors = On
allow_url_include = Off
max_execution_time = 1200
memory_limit = 512M
session.gc_maxlifetime = 1440
date.timezone = Europe/Rome